### ISSUE TITLE
:sparkles: MicroLib.Collections

### ISSUE THREAD

**Issue by Kalkwst** [Kalkwst/MicroLib#30]
Feel free to propose and/or implement new data structures, I will add them to the list below :)

## Lists
- [ ] Doubly Linked List (see issue [here](https://github.com/Kalkwst/MicroLib/issues/21))
- [ ] Skip List (see issue [here](https://github.com/Kalkwst/MicroLib/issues/22))
- [ ] Unrolled List (see issue [here](https://github.com/Kalkwst/MicroLib/issues/23))
- [ ] Self-Organizing List (see issue [here](https://github.com/Kalkwst/MicroLib/issues/24))
- [ ] Tree-List (see issue [here](https://github.com/Kalkwst/MicroLib/issues/25))

#### List Decorators

- [ ] Predicated Decorator (see issue [here](https://github.com/Kalkwst/MicroLib/issues/26))
- [ ] Transformer Decorator (see issue [here](https://github.com/Kalkwst/MicroLib/issues/27))
- [ ] Lazy Decorator (see issue[here](https://github.com/Kalkwst/MicroLib/issues/28))
- [ ] SetUnique Decorator (see issue [here](https://github.com/Kalkwst/MicroLib/issues/29))

## Queues

- [ ] Circular FIFO Queue (see issue [here](https://github.com/Kalkwst/MicroLib/issues/31))

#### Queue Decorators

- [ ] Predicated Decorator (see issue [here](https://github.com/Kalkwst/MicroLib/issues/32))
- [ ] Transformer Decorator (see issue [here](https://github.com/Kalkwst/MicroLib/issues/33))
- [ ] SetUnique Decorator (see issue [here](https://github.com/Kalkwst/MicroLib/issues/34))

### Binary Trees

- [ ] AVL Tree (see issue [here](https://github.com/Kalkwst/MicroLib/issues/35))
- [ ] Binary Search Tree (see issue [here](https://github.com/Kalkwst/MicroLib/issues/36))
- [ ] Cartesian Tree (see issue [here](https://github.com/Kalkwst/MicroLib/issues/37))
- [ ] Red-Black Tree (see issue [here](https://github.com/Kalkwst/MicroLib/issues/38))
- [ ] Rope Tree (see issue [here](https://github.com/Kalkwst/MicroLib/issues/39))
- [ ] Scapegoat Tree (see issue [here](https://github.com/Kalkwst/MicroLib/issues/40))
- [ ] Splay Tree (see issue [here](https://github.com/Kalkwst/MicroLib/issues/41))
- [ ] Threaded Binary Tree (see issue [here](https://github.com/Kalkwst/MicroLib/issues/42))
- [ ] Treap Tree (see issue [here](https://github.com/Kalkwst/MicroLib/issues/43)) 

### B-Trees

- [ ] 2-3 Tree (see issue [here](https://github.com/Kalkwst/MicroLib/issues/44))
- [ ] 2-3-4 Tree (see issue [here](https://github.com/Kalkwst/MicroLib/issues/45))

### Bit-Splice Trees

- [ ] Radix Tree (see issue [here](https://github.com/Kalkwst/MicroLib/issues/46))
- [ ] Suffix Tree (see issue [here](https://github.com/Kalkwst/MicroLib/issues/47))
